### ISSUE TITLE
on_player_settings_clicked() function uses .querySelectorAll('.player-settings-icon')

### ISSUE THREAD

**Issue by samolukadjo** [tusx/better-mobile-youtube#3]
There is only one settings icon on the page, so why is it this way?

**Comment by tusx** [comment]
i think there was a reason for doing it in earlier versions, but i can't be sure if it needs to be there now or not.

i will check that once I'm at my pc.

**Comment by tusx** [comment]
im closing this issue because i believe you fixed this in recent pr
