### ISSUE TITLE
Speed up start times

### ISSUE THREAD

**Issue by samolukadjo** [tusx/better-mobile-youtube#5]
* Change extension functions to start based on loading status of necessary elements

**Comment by samolukadjo** [comment]
Already started work on this

**Comment by tusx** [comment]
that is great idea. i have assigned this to you. 

thanks for your help.🫡

**Comment by samolukadjo** [comment]
While this is now most of the way there, if the commented out features ever get re-enabled they will need to have some changes  as well.

**Comment by tusx** [comment]
i will make PR where all the commented code be removed.
i currently have no plans on re-implementing any of it back.

**Comment by tusx** [comment]
e4b16729bf4f21f51c944b8399761235f06c7431

Done

**Comment by tusx** [comment]
older dev branch has conflict so it was deleted and new dev branch was created. the above mentioned changes were moved onto new dev branch
